add landing page hero section, add own style sheet for landing page, …
Devslopes-Herd/BaseCamp-LandingPage pull request #25
Opened 2022-09-14 13:02 UTC by SamGamgy

…update global 'body' styles

2022-09-14 13:06 UTC, SamGamgy commented
accidentally altered button.css style sheet. I removed my redundant code and commited for review

2022-09-14 14:04 UTC, mikesz88 requested changes

2022-09-14 14:04 UTC, mikesz88 commented on main/landing-page.css
> +    margin-left: 28%;
It is not recommended to use percentages. Changing this to rems is my recommendation.

2022-09-14 14:04 UTC, mikesz88 commented on main/landing-page.css
> +    margin-right: 28%;
It is not recommended to use percentages. Changing this to rems is my recommendation.

2022-09-14 14:04 UTC, mikesz88 commented on main/landing-page.css
> +    padding:5% 25%;
It is not recommended to use percentages. Changing this to rems is my recommendation. pixels can work here.

2022-09-15 02:05 UTC, mikesz88 approved these changes
lgtm

2022-09-15 02:05 UTC, merged